extends SceneTree
const Map0=preload("res://components/start_tilemap_32.gd")
const Plan=preload("res://components/map0_ground_plan_32.gd")

func _initialize()->void:
	ProjectSettings.set_setting("sonnenhain/terrain/gba_enabled",true)
	ProjectSettings.set_setting("sonnenhain/terrain/force_rebake",true)
	var started:=Time.get_ticks_msec()
	Map0.prepare(Callable())
	DirAccess.make_dir_recursive_absolute(Map0.BAKED_PATH)
	for id in Plan.CHUNK_ORDER:
		var region:Rect2i=Plan.CHUNKS[id]["cells"]
		var image:=Map0.floor_image.get_region(Rect2i(region.position*32,region.size*32))
		assert(image.save_png(Map0.BAKED_PATH+str(id)+".png")==OK)
	var file:=FileAccess.open("res://components/terrain/gba_bake_manifest.gd",FileAccess.WRITE)
	file.store_string("extends RefCounted\n# Generated by tools/bake_gba_map0.gd; detects changed source pixels and map layout.\nconst SIGNATURE:=\"%s\"\n"%Map0.bake_signature)
	file.close()
	print("GBA_BAKE_OK six small opaque chunk PNGs, sha256=",Map0.bake_signature," elapsed_ms=",Time.get_ticks_msec()-started)
	quit()
